package com.gabrielpc.enginesoundsinstaller;

import android.app.Activity;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.os.ParcelFileDescriptor;
import android.content.pm.ProviderInfo;
import android.content.pm.PackageManager;
import android.util.JsonReader;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.ScrollView;
import java.io.*;
import java.util.*;

/** Installs the banks embedded in this flavor into the dashboard's private bank store. */
public final class AudioInstallerActivity extends Activity {
    private static final String ORIGINAL_GROUP="original_cars_pack", MODDED_GROUP="modded_car_packs";
    private static final Uri STORE=Uri.parse("content://com.gabrielpc.enginesoundsimulator.fmodbanks/packs");
    private final Handler main=new Handler(Looper.getMainLooper()); private TextView status,logView; private ProgressBar progress; private Button install,delete; private List<Pack> packs=List.of();
    @Override public void onCreate(Bundle state){super.onCreate(state);Thread.setDefaultUncaughtExceptionHandler((thread,error)->{log("UNCAUGHT "+thread.getName()+": "+error);for(StackTraceElement frame:error.getStackTrace())log("  at "+frame);});setContentView(content());try{packs=readIndex();idle();log("Ready. Payload="+BuildConfig.PAYLOAD_GROUP+", packs="+packs.size());}catch(Exception e){status.setText("This installer has no embedded bank payload.");log("INDEX ERROR "+e);install.setEnabled(false);}}
    private View content(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(48,36,48,36);root.setGravity(Gravity.CENTER_VERTICAL);root.setBackgroundColor(0xff05080a);root.addView(text("ENGINE FMOD BANK INSTALLER",28,0xff00d7e8));root.addView(text((MODDED_GROUP.equals(BuildConfig.PAYLOAD_GROUP)?"MODDED CARS":BuildConfig.PAYLOAD_GROUP.equals("probe_payload")?"CONTENT PROVIDER TEST":"ORIGINAL ASSETTO CORSA CARS")+" · EMBEDDED PAYLOAD",17,0xffd5e2e8));status=text("Preparing…",18,0xffffffff);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.topMargin=28;root.addView(status,sp);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);root.addView(progress,new LinearLayout.LayoutParams(-1,18));LinearLayout actions=new LinearLayout(this);actions.setPadding(0,28,0,0);install=action(BuildConfig.PAYLOAD_GROUP.equals("probe_payload")?"COPY TEST FILE":"INSTALL "+(MODDED_GROUP.equals(BuildConfig.PAYLOAD_GROUP)?"MODDED":"ORIGINAL")+" CARS",()->install(BuildConfig.PAYLOAD_GROUP));actions.addView(install);delete=action("DELETE ALL",this::deleteAll);LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(-2,-2);dp.leftMargin=20;actions.addView(delete,dp);root.addView(actions);LinearLayout probes=new LinearLayout(this);probes.addView(action("PROBE PROVIDER",()->probe("provider",this::probeProvider)));probes.addView(action("PROBE AUTHORITY",()->probe("authority",this::probeAuthority)));probes.addView(action("PROBE STORAGE",()->probe("storage",this::probeStorage)));probes.addView(action("CLEAR LOG",()->{logView.setText("");clearLog();}));root.addView(probes);logView=text("Diagnostics will appear here.",13,0xff9ab0ba);logView.setPadding(0,8,0,8);ScrollView scroll=new ScrollView(this);scroll.addView(logView,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));return root;}
    private Button action(String label,Runnable run){Button b=new Button(this);b.setText(label);b.setOnClickListener(v->run.run());return b;}
    private void idle(){Set<String> done=installed();long total=packs.stream().filter(p->BuildConfig.PAYLOAD_GROUP.equals(p.group)&&!p.dep).count(),count=packs.stream().filter(p->BuildConfig.PAYLOAD_GROUP.equals(p.group)&&!p.dep&&done.contains(p.group+"/"+p.id)).count();status.setText((MODDED_GROUP.equals(BuildConfig.PAYLOAD_GROUP)?"Modded":"Original")+" installer · "+count+"/"+total+" cars installed");}
    private void install(String group){busy(true);log("INSTALL START group="+group);new Thread(()->{List<Pack> selected=new ArrayList<>();for(Pack p:packs)if(group.equals(p.group)||p.dep)selected.add(p);long total=selected.stream().mapToLong(p->p.bytes).sum(),copied=0;try{for(Pack p:selected){post("Installing "+p.name,copied,total);copied+=copy(p,total,copied);waitFor(p.group,p.id);}main.post(()->{status.setText("Import completed successfully.");progress.setProgress(1000);log("INSTALL COMPLETE");idle();busy(false);});}catch(Exception e){log("INSTALL ERROR "+e);main.post(()->{status.setText("Installation failed: "+e.getMessage());busy(false);});}},"install-embedded-fmod-banks").start();}
    private long copy(Pack p,long total,long completed)throws IOException{Uri dest=Uri.parse(STORE+"/"+p.group+"/"+p.id);ParcelFileDescriptor fd=getContentResolver().openFileDescriptor(dest,"w");if(fd==null)throw new IOException("Engine Sounds Simulator is not installed");long n=0;try(InputStream in=getAssets().open("packs/"+p.asset);FileOutputStream out=new FileOutputStream(fd.getFileDescriptor())){byte[] b=new byte[262144];int r;while((r=in.read(b))>=0){out.write(b,0,r);n+=r;post("Installing "+p.name,completed+n,total);}}finally{fd.close();}return n;}
    private void waitFor(String group,String id)throws IOException{for(int i=0;i<100;i++){if(installed().contains(group+"/"+id))return;try{Thread.sleep(100);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IOException("Installation interrupted",e);}}throw new IOException("Dashboard did not publish "+id);}
    private void deleteAll(){busy(true);new Thread(()->{try{getContentResolver().delete(STORE,null,null);main.post(()->{status.setText("All installed FMOD banks were deleted.");progress.setProgress(0);busy(false);});}catch(Exception e){main.post(()->{status.setText("Delete failed: "+e.getMessage());busy(false);});}},"delete-fmod-banks").start();}
    private Set<String> installed(){Set<String> ids=new HashSet<>();try(Cursor c=getContentResolver().query(STORE,null,null,null,null)){if(c==null)return ids;int g=c.getColumnIndex("group"),i=c.getColumnIndex("id");while(c.moveToNext()&&g>=0&&i>=0)ids.add(c.getString(g)+"/"+c.getString(i));}return ids;}
    private void post(String msg,long n,long total){main.post(()->{status.setText(msg+" — "+n/(1024*1024)+" / "+total/(1024*1024)+" MB");progress.setProgress(total==0?0:(int)Math.min(1000,n*1000/total));});}
    private void probe(String name,Runnable work){log("PROBE START "+name);new Thread(()->{try{work.run();log("PROBE OK "+name);}catch(Exception e){log("PROBE ERROR "+name+": "+e);}},"probe-"+name).start();}
    private void probeProvider(){try(Cursor c=getContentResolver().query(STORE,null,null,null,null)){if(c==null)throw new IOException("provider returned null cursor");log("provider columns="+c.getColumnCount()+", rows="+c.getCount());}catch(Exception e){throw new RuntimeException(e);}}
    private void probeAuthority(){ProviderInfo info=getPackageManager().resolveContentProvider(STORE.getAuthority(),PackageManager.GET_META_DATA);if(info==null)throw new IllegalStateException("authority not registered: "+STORE.getAuthority());log("authority package="+info.packageName+" exported="+info.exported+" enabled="+info.enabled+" process="+info.processName);}
    private void probeStorage(){File external=getExternalFilesDir(null);File internal=getFilesDir();log("external="+external+" free="+external.getFreeSpace()+" bytes");log("internal="+internal+" free="+internal.getFreeSpace()+" bytes");log("payload packs="+packs.size()+" total="+packs.stream().mapToLong(p->p.bytes).sum()+" bytes");}
    private File logFile(){return new File(getExternalFilesDir(null),"installer-diagnostic.log");}
    private synchronized void log(String message){String line=System.currentTimeMillis()+" "+message;main.post(()->{if(logView!=null){String old=logView.getText().toString();String[] lines=(old+"\n"+line).split("\n");StringBuilder shown=new StringBuilder();for(int i=Math.max(0,lines.length-12);i<lines.length;i++)shown.append(lines[i]).append('\n');logView.setText(shown.toString());}});try(FileWriter out=new FileWriter(logFile(),true)){out.write(line+"\n");}catch(IOException ignored){}}
    private void clearLog(){try(FileOutputStream out=new FileOutputStream(logFile(),false)){}catch(IOException ignored){}}
    private void busy(boolean b){install.setEnabled(!b);delete.setEnabled(!b);} private TextView text(String v,int s,int c){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);return t;}
    private List<Pack> readIndex()throws IOException{List<Pack> out=new ArrayList<>();try(JsonReader r=new JsonReader(new InputStreamReader(getAssets().open("packs/index.json")))){r.beginObject();while(r.hasNext()){if("packs".equals(r.nextName())){r.beginArray();while(r.hasNext()){Pack p=readPack(r);if(p.active&&(BuildConfig.PAYLOAD_GROUP.equals(p.group)||p.dep))out.add(p);}r.endArray();}else r.skipValue();}r.endObject();}if(out.isEmpty())throw new IOException("Pack index is empty");return out;}
    private Pack readPack(JsonReader r)throws IOException{String id=null,name=null,asset=null,group=null;long bytes=0;boolean active=false,dep=false;r.beginObject();while(r.hasNext()){switch(r.nextName()){case"id":id=r.nextString();break;case"name":name=r.nextString();break;case"asset":asset=r.nextString();break;case"group":group=r.nextString();break;case"bytes":bytes=r.nextLong();break;case"active":active=r.nextBoolean();break;case"dependency":dep=r.nextBoolean();break;default:r.skipValue();}}r.endObject();if(id==null||name==null||asset==null||group==null||bytes<=0)throw new IOException("Invalid pack index entry");return new Pack(id,name,asset,bytes,group,active,dep);}
    private static final class Pack{final String id,name,asset,group;final long bytes;final boolean active,dep;Pack(String i,String n,String a,long b,String g,boolean ac,boolean d){id=i;name=n;asset=a;bytes=b;group=g;active=ac;dep=d;}}
}
