package com.gabrielpc.enginesoundsimulator.catalog

internal data class OfficialCarSeed(val id: String, val displayName: String, val brand: String = "")

/** Immutable minimal index. Generated catalogs and every media byte remain outside the APK. */
internal object OfficialCarIndex {
    val cars: List<OfficialCarSeed> = listOf(
        OfficialCarSeed("abarth500", "Abarth 500 SS"),
        OfficialCarSeed("abarth500_s1", "Abarth 500 SS Step1"),
        OfficialCarSeed("alfa_romeo_giulietta_qv", "Alfa Romeo Giulietta Q.V."),
        OfficialCarSeed("alfa_romeo_giulietta_qv_le", "Alfa Romeo Giulietta Q.V. Launch Ed."),
        OfficialCarSeed("bmw_1m", "BMW 1M"),
        OfficialCarSeed("bmw_1m_s3", "BMW 1M Stage 3"),
        OfficialCarSeed("bmw_m3_e30", "BMW M3 E30"),
        OfficialCarSeed("bmw_m3_e30_drift", "BMW M3 E30 Drift"),
        OfficialCarSeed("bmw_m3_e30_dtm", "BMW M3 E30 GrA 92"),
        OfficialCarSeed("bmw_m3_e30_gra", "BMW M3 E30 grA"),
        OfficialCarSeed("bmw_m3_e30_s1", "BMW M3 E30 Step1"),
        OfficialCarSeed("bmw_m3_e92", "BMW M3 E92"),
        OfficialCarSeed("bmw_m3_e92_drift", "BMW M3 E92 Drift"),
        OfficialCarSeed("bmw_m3_e92_s1", "BMW M3 E92 S1"),
        OfficialCarSeed("bmw_m3_gt2", "BMW M3 GT2"),
        OfficialCarSeed("bmw_z4", "BMW Z4"),
        OfficialCarSeed("bmw_z4_drift", "BMW Z4 Drift"),
        OfficialCarSeed("bmw_z4_gt3", "BMW Z4 GT3"),
        OfficialCarSeed("bmw_z4_s1", "BMW Z4 Step1"),
        OfficialCarSeed("ferrari_312t", "Ferrari 312T"),
        OfficialCarSeed("ferrari_458", "Ferrari 458 Italia"),
        OfficialCarSeed("ferrari_458_gt2", "Ferrari 458 GT2"),
        OfficialCarSeed("ferrari_458_s3", "Ferrari 458 Italia Stage 3"),
        OfficialCarSeed("ferrari_599xxevo", "Ferrari 599XX EVO"),
        OfficialCarSeed("ferrari_f40", "Ferrari F40"),
        OfficialCarSeed("ferrari_f40_s3", "Ferrari F40 Step3"),
        OfficialCarSeed("ferrari_laferrari", "Ferrari LaFerrari"),
        OfficialCarSeed("ks_abarth500_assetto_corse", "Abarth 500 Assetto Corse"),
        OfficialCarSeed("ks_abarth_595ss", "Abarth 595 SS"),
        OfficialCarSeed("ks_abarth_595ss_s1", "Abarth 595 SS Step1"),
        OfficialCarSeed("ks_abarth_595ss_s2", "Abarth 595 SS Step2"),
        OfficialCarSeed("ks_alfa_33_stradale", "Alfa Romeo 33 Stradale"),
        OfficialCarSeed("ks_alfa_giulia_qv", "Alfa Romeo Giulia Quadrifoglio"),
        OfficialCarSeed("ks_alfa_mito_qv", "Alfa Romeo Mito QV"),
        OfficialCarSeed("ks_alfa_romeo_155_v6", "Alfa Romeo 155 TI V6", "Alfa Romeo"),
        OfficialCarSeed("ks_alfa_romeo_4c", "Alfa Romeo 4C"),
        OfficialCarSeed("ks_alfa_romeo_gta", "Alfa Romeo GTA"),
        OfficialCarSeed("ks_audi_a1s1", "Audi S1"),
        OfficialCarSeed("ks_audi_r18_etron_quattro", "Audi R18 e-tron quattro 2014"),
        OfficialCarSeed("ks_audi_r8_lms", "Audi R8 LMS Ultra"),
        OfficialCarSeed("ks_audi_r8_lms_2016", "Audi R8 LMS 2016"),
        OfficialCarSeed("ks_audi_r8_plus", "Audi R8 Plus"),
        OfficialCarSeed("ks_audi_sport_quattro", "Audi Sport quattro", "Audi"),
        OfficialCarSeed("ks_audi_sport_quattro_rally", "Audi Sport quattro S1 E2"),
        OfficialCarSeed("ks_audi_sport_quattro_s1", "Audi Sport quattro Step1", "Audi"),
        OfficialCarSeed("ks_audi_tt_cup", "Audi TT Cup"),
        OfficialCarSeed("ks_audi_tt_vln", "Audi TT RS (VLN)"),
        OfficialCarSeed("ks_bmw_m235i_racing", "BMW M235i Racing"),
        OfficialCarSeed("ks_bmw_m4", "BMW M4"),
        OfficialCarSeed("ks_bmw_m4_akrapovic", "BMW M4 Akrapovic"),
        OfficialCarSeed("ks_corvette_c7_stingray", "Chevrolet Corvette C7 Stingray"),
        OfficialCarSeed("ks_corvette_c7r", "Chevrolet Corvette C7R"),
        OfficialCarSeed("ks_ferrari_250_gto", "Ferrari 250 GTO"),
        OfficialCarSeed("ks_ferrari_288_gto", "Ferrari GTO"),
        OfficialCarSeed("ks_ferrari_312_67", "Ferrari 312/67"),
        OfficialCarSeed("ks_ferrari_330_p4", "Ferrari 330 P4"),
        OfficialCarSeed("ks_ferrari_488_gt3", "Ferrari 488 GT3"),
        OfficialCarSeed("ks_ferrari_488_gtb", "Ferrari 488 GTB"),
        OfficialCarSeed("ks_ferrari_812_superfast", "Ferrari 812 Superfast"),
        OfficialCarSeed("ks_ferrari_f138", "Ferrari F138"),
        OfficialCarSeed("ks_ferrari_f2004", "Ferrari F2004"),
        OfficialCarSeed("ks_ferrari_fxx_k", "Ferrari FXX K"),
        OfficialCarSeed("ks_ferrari_sf15t", "Ferrari SF15-T"),
        OfficialCarSeed("ks_ferrari_sf70h", "Ferrari SF70H"),
        OfficialCarSeed("ks_ford_escort_mk1", "Ford Escort Mk1"),
        OfficialCarSeed("ks_ford_gt40", "Ford GT40"),
        OfficialCarSeed("ks_ford_mustang_2015", "Ford Mustang 2015"),
        OfficialCarSeed("ks_glickenhaus_scg003", "Scuderia Glickenhaus SCG003"),
        OfficialCarSeed("ks_lamborghini_aventador_sv", "Lamborghini Aventador SV"),
        OfficialCarSeed("ks_lamborghini_countach", "Lamborghini Countach"),
        OfficialCarSeed("ks_lamborghini_countach_s1", "Lamborghini Countach S1"),
        OfficialCarSeed("ks_lamborghini_gallardo_sl", "Lamborghini Gallardo Superleggera"),
        OfficialCarSeed("ks_lamborghini_gallardo_sl_s3", "Lamborghini Gallardo Superleggera S3"),
        OfficialCarSeed("ks_lamborghini_huracan_gt3", "Lamborghini Huracan GT3"),
        OfficialCarSeed("ks_lamborghini_huracan_performante", "Lamborghini Huracan Performante"),
        OfficialCarSeed("ks_lamborghini_huracan_st", "Lamborghini Huracan ST"),
        OfficialCarSeed("ks_lamborghini_miura_sv", "Lamborghini Miura P400 SV"),
        OfficialCarSeed("ks_lamborghini_sesto_elemento", "Lamborghini Sesto Elemento"),
        OfficialCarSeed("ks_lotus_25", "Lotus Type 25", "Lotus Classic Cars"),
        OfficialCarSeed("ks_lotus_3_eleven", "Lotus 3-Eleven"),
        OfficialCarSeed("ks_lotus_72d", "Lotus 72D"),
        OfficialCarSeed("ks_maserati_250f_12cyl", "Maserati 250F 12 cylinder"),
        OfficialCarSeed("ks_maserati_250f_6cyl", "Maserati 250F 6 cylinder"),
        OfficialCarSeed("ks_maserati_alfieri", "Maserati Alfieri"),
        OfficialCarSeed("ks_maserati_gt_mc_gt4", "Maserati GranTurismo MC GT4"),
        OfficialCarSeed("ks_maserati_levante", "Maserati Levante S"),
        OfficialCarSeed("ks_maserati_mc12_gt1", "Maserati MC12 GT1"),
        OfficialCarSeed("ks_maserati_quattroporte", "Maserati Quattroporte GTS", "Maserati"),
        OfficialCarSeed("ks_mazda_787b", "Mazda 787B"),
        OfficialCarSeed("ks_mazda_miata", "Mazda MX5 NA"),
        OfficialCarSeed("ks_mazda_mx5_cup", "Mazda MX5 Cup"),
        OfficialCarSeed("ks_mazda_mx5_nd", "Mazda MX5 ND"),
        OfficialCarSeed("ks_mazda_rx7_spirit_r", "Mazda RX7 Spirit R"),
        OfficialCarSeed("ks_mazda_rx7_tuned", "Mazda RX7 Tuned"),
        OfficialCarSeed("ks_mclaren_570s", "McLaren 570S"),
        OfficialCarSeed("ks_mclaren_650_gt3", "McLaren 650S GT3"),
        OfficialCarSeed("ks_mclaren_f1_gtr", "McLaren F1 GTR 96"),
        OfficialCarSeed("ks_mclaren_p1", "McLaren P1"),
        OfficialCarSeed("ks_mclaren_p1_gtr", "McLaren P1 GTR"),
        OfficialCarSeed("ks_mercedes_190_evo2", "Mercedes 190 EVO 2"),
        OfficialCarSeed("ks_mercedes_amg_gt3", "Mercedes AMG GT3"),
        OfficialCarSeed("ks_mercedes_c9", "Sauber-Mercedes C9"),
        OfficialCarSeed("ks_nissan_370z", "Nissan 370Z Nismo"),
        OfficialCarSeed("ks_nissan_gtr", "Nissan GT-R Nismo"),
        OfficialCarSeed("ks_nissan_gtr_gt3", "Nissan Nismo GT3"),
        OfficialCarSeed("ks_nissan_skyline_r34", "Nissan GT-R R34 V-Spec"),
        OfficialCarSeed("ks_pagani_huayra_bc", "Pagani Huayra BC"),
        OfficialCarSeed("ks_porsche_718_boxster_s", "Porsche 718 Boxster S"),
        OfficialCarSeed("ks_porsche_718_boxster_s_pdk", "Porsche 718 Boxster S PDK"),
        OfficialCarSeed("ks_porsche_718_cayman_s", "Porsche 718 Cayman S"),
        OfficialCarSeed("ks_porsche_718_spyder_rs", "Porsche 718 RS 60 Spyder"),
        OfficialCarSeed("ks_porsche_908_lh", "Porsche 908 LH"),
        OfficialCarSeed("ks_porsche_911_carrera_rsr", "Porsche 911 Carrera RSR 3.0"),
        OfficialCarSeed("ks_porsche_911_gt1", "Porsche 911 GT1-98"),
        OfficialCarSeed("ks_porsche_911_gt3_cup_2017", "Porsche 911 GT3 Cup 2017"),
        OfficialCarSeed("ks_porsche_911_gt3_r_2016", "Porsche 911 GT3 R 2016"),
        OfficialCarSeed("ks_porsche_911_gt3_rs", "Porsche 911 GT3 RS"),
        OfficialCarSeed("ks_porsche_911_r", "Porsche 911 R"),
        OfficialCarSeed("ks_porsche_911_rsr_2017", "Porsche 911 RSR 2017"),
        OfficialCarSeed("ks_porsche_917_30", "Porsche 917/30 Spyder"),
        OfficialCarSeed("ks_porsche_917_k", "Porsche 917 K"),
        OfficialCarSeed("ks_porsche_918_spyder", "Porsche 918 Spyder"),
        OfficialCarSeed("ks_porsche_919_hybrid_2015", "Porsche 919 Hybrid 2015"),
        OfficialCarSeed("ks_porsche_919_hybrid_2016", "Porsche 919 Hybrid 2016"),
        OfficialCarSeed("ks_porsche_935_78_moby_dick", "Porsche 935/78 \"Moby Dick\""),
        OfficialCarSeed("ks_porsche_962c_longtail", "Porsche 962 C Long Tail"),
        OfficialCarSeed("ks_porsche_962c_shorttail", "Porsche 962 C Short Tail"),
        OfficialCarSeed("ks_porsche_991_carrera_s", "Porsche 911 Carrera S"),
        OfficialCarSeed("ks_porsche_991_turbo_s", "Porsche 911 Turbo S"),
        OfficialCarSeed("ks_porsche_cayenne", "Porsche Cayenne Turbo S"),
        OfficialCarSeed("ks_porsche_cayman_gt4_clubsport", "Porsche Cayman GT4 Clubsport"),
        OfficialCarSeed("ks_porsche_cayman_gt4_std", "Porsche Cayman GT4"),
        OfficialCarSeed("ks_porsche_macan", "Porsche Macan Turbo"),
        OfficialCarSeed("ks_porsche_panamera", "Porsche Panamera Turbo"),
        OfficialCarSeed("ks_praga_r1", "Praga R1"),
        OfficialCarSeed("ks_ruf_rt12r", "RUF RT12 R"),
        OfficialCarSeed("ks_ruf_rt12r_awd", "RUF RT12 R AWD"),
        OfficialCarSeed("ks_toyota_ae86", "TOYOTA AE86"),
        OfficialCarSeed("ks_toyota_ae86_drift", "TOYOTA AE86 Drift"),
        OfficialCarSeed("ks_toyota_ae86_tuned", "TOYOTA AE86 Tuned"),
        OfficialCarSeed("ks_toyota_celica_st185", "Toyota Celica ST185 4WD Turbo"),
        OfficialCarSeed("ks_toyota_gt86", "Toyota GT86"),
        OfficialCarSeed("ks_toyota_supra_mkiv", "Toyota Supra MKIV"),
        OfficialCarSeed("ks_toyota_supra_mkiv_drift", "Toyota Supra MKIV Drift", "Toyota"),
        OfficialCarSeed("ks_toyota_supra_mkiv_tuned", "Toyota Supra MKIV Time Attack"),
        OfficialCarSeed("ks_toyota_ts040", "Toyota TS040 Hybrid 2014"),
        OfficialCarSeed("ktm_xbow_r", "KTM X-Bow R"),
        OfficialCarSeed("lotus_2_eleven", "Lotus 2-Eleven"),
        OfficialCarSeed("lotus_2_eleven_gt4", "Lotus 2-Eleven GT4"),
        OfficialCarSeed("lotus_49", "Lotus 49"),
        OfficialCarSeed("lotus_98t", "Lotus 98T"),
        OfficialCarSeed("lotus_elise_sc", "Lotus Elise SC"),
        OfficialCarSeed("lotus_elise_sc_s1", "Lotus Elise SC Step1"),
        OfficialCarSeed("lotus_elise_sc_s2", "Lotus Elise SC Step2"),
        OfficialCarSeed("lotus_evora_gtc", "Lotus Evora GTC"),
        OfficialCarSeed("lotus_evora_gte", "Lotus Evora GTE"),
        OfficialCarSeed("lotus_evora_gte_carbon", "Lotus Evora GTE Carbon"),
        OfficialCarSeed("lotus_evora_gx", "Lotus Evora GX"),
        OfficialCarSeed("lotus_evora_s", "Lotus Evora S"),
        OfficialCarSeed("lotus_evora_s_s2", "Lotus Evora S Stage 2"),
        OfficialCarSeed("lotus_exige_240", "Lotus Exige 240R"),
        OfficialCarSeed("lotus_exige_240_s3", "Lotus Exige 240R Stage 3"),
        OfficialCarSeed("lotus_exige_s", "Lotus Exige S"),
        OfficialCarSeed("lotus_exige_s_roadster", "Lotus Exige S"),
        OfficialCarSeed("lotus_exige_scura", "Lotus Exige Scura"),
        OfficialCarSeed("lotus_exige_v6_cup", "Lotus Exige V6 Cup"),
        OfficialCarSeed("lotus_exos_125", "Lotus Exos 125"),
        OfficialCarSeed("lotus_exos_125_s1", "Lotus Exos 125 S1"),
        OfficialCarSeed("mclaren_mp412c", "McLaren MP4-12C"),
        OfficialCarSeed("mclaren_mp412c_gt3", "McLaren MP4-12C GT3"),
        OfficialCarSeed("mercedes_sls", "Mercedes SLS AMG"),
        OfficialCarSeed("mercedes_sls_gt3", "Mercedes SLS AMG GT3"),
        OfficialCarSeed("p4-5_2011", "P4/5 Competizione 2011"),
        OfficialCarSeed("pagani_huayra", "Pagani Huayra"),
        OfficialCarSeed("pagani_zonda_r", "Pagani Zonda R"),
        OfficialCarSeed("ruf_yellowbird", "Ruf Yellowbird"),
        OfficialCarSeed("shelby_cobra_427sc", "Shelby Cobra 427 S/C"),
        OfficialCarSeed("tatuusfa1", "Tatuus FA01"),
    )

    init {
        check(cars.size == 178)
        check(cars.map { it.id }.toSet().size == cars.size)
    }
}
