package com.gabrielpc.enginesoundsimulator.audio

/** A selectable car is metadata only; all engine and gearbox values come from its physics pack. */
internal data class FmodBankProfile(
    val id: String,
    val displayName: String,
    val previewAssetName: String,
    val bankPackId: String = id,
    val packGroup: String = FmodBankProfiles.originalCarsPackId,
)

/** Catalog metadata for both installable bank groups. Runtime selection filters to installed packs. */
internal object FmodBankProfiles {
    const val originalCarsPackId = "original_cars_pack"
    const val moddedCarsPackId = "modded_car_packs"
    const val commonStringsPackId = "assetto-common-strings"
    const val commonPackId = "assetto-common"

    val default = profile("alfa-romeo-4c", "Alfa Romeo 4C")

    val all: List<FmodBankProfile> = listOf(
        default,
        profile("assetto-abarth500-s1", "Abarth500 S1"),
        profile("assetto-alfa-romeo-giulietta-qv", "Alfa Romeo Giulietta Qv"),
        profile("assetto-alfa-romeo-giulietta-qv-le", "Alfa Romeo Giulietta Qv Le"),
        profile("assetto-audi-r8-lms-2016", "Audi R8 LMS 2016"),
        profile("assetto-audi-r8-plus", "Audi R8 Plus"),
        profile("assetto-audi-tt-cup", "Audi TT Cup"),
        profile("assetto-bmw-1m-s3", "Bmw 1M S3"),
        profile("assetto-bmw-m3-e92-s1", "Bmw M3 E92 S1"),
        profile("assetto-bmw-m3-gt2", "Bmw M3 Gt2"),
        profile("assetto-bmw-m4", "BMW M4"),
        profile("assetto-bmw-z4-gt3", "Bmw Z4 Gt3"),
        profile("assetto-common", "Assetto Corsa shared audio"),
        profile("assetto-common-strings", "Assetto Corsa event strings"),
        profile("assetto-corvette-c7-stingray", "Chevrolet Corvette C7 Stingray"),
        profile("assetto-ferrari-458-gt2", "Ferrari 458 GT2"),
        profile("assetto-ferrari-458-s3", "Ferrari 458 S3"),
        profile("assetto-ferrari-488-gt3", "Ferrari 488 GT3"),
        profile("assetto-ferrari-488-gtb", "Ferrari 488 GTB"),
        profile("assetto-ferrari-599xxevo", "Ferrari 599Xxevo"),
        profile("assetto-ferrari-fxx-k", "Ferrari FXX K"),
        profile("assetto-ferrari-laferrari", "Ferrari LaFerrari"),
        profile("assetto-ks-abarth-595ss", "Ks Abarth 595Ss"),
        profile("assetto-ks-abarth-595ss-s1", "Ks Abarth 595Ss S1"),
        profile("assetto-ks-abarth-595ss-s2", "Ks Abarth 595Ss S2"),
        profile("assetto-ks-abarth500-assetto-corse", "Ks Abarth500 Assetto Corse"),
        profile("assetto-ks-alfa-giulia-qv", "Ks Alfa Giulia Qv"),
        profile("assetto-ks-alfa-mito-qv", "Ks Alfa Mito Qv"),
        profile("assetto-ks-audi-a1s1", "Ks Audi A1S1"),
        profile("assetto-ks-audi-r18-etron-quattro", "Ks Audi R18 Etron Quattro"),
        profile("assetto-ks-audi-r8-lms", "Ks Audi R8 Lms"),
        profile("assetto-ks-audi-tt-vln", "Ks Audi Tt Vln"),
        profile("assetto-ks-bmw-m235i-racing", "Ks Bmw M235I Racing"),
        profile("assetto-ks-bmw-m4-akrapovic", "Ks Bmw M4 Akrapovic"),
        profile("assetto-ks-corvette-c7r", "Ks Corvette C7R"),
        profile("assetto-ks-ferrari-812-superfast", "Ks Ferrari 812 Superfast"),
        profile("assetto-ks-ferrari-f138", "Ks Ferrari F138"),
        profile("assetto-ks-ferrari-f2004", "Ks Ferrari F2004"),
        profile("assetto-ks-ferrari-sf15t", "Ks Ferrari Sf15T"),
        profile("assetto-ks-ferrari-sf70h", "Ks Ferrari Sf70H"),
        profile("assetto-ks-ford-mustang-2015", "Ks Ford Mustang 2015"),
        profile("assetto-ks-glickenhaus-scg003", "Ks Glickenhaus Scg003"),
        profile("assetto-ks-lamborghini-gallardo-sl-s3", "Ks Lamborghini Gallardo Sl S3"),
        profile("assetto-ks-lamborghini-huracan-gt3", "Ks Lamborghini Huracan Gt3"),
        profile("assetto-ks-lamborghini-sesto-elemento", "Ks Lamborghini Sesto Elemento"),
        profile("assetto-ks-maserati-alfieri", "Ks Maserati Alfieri"),
        profile("assetto-ks-maserati-gt-mc-gt4", "Ks Maserati Gt Mc Gt4"),
        profile("assetto-ks-maserati-levante", "Ks Maserati Levante"),
        profile("assetto-ks-maserati-mc12-gt1", "Ks Maserati Mc12 Gt1"),
        profile("assetto-ks-maserati-quattroporte", "Maserati Quattroporte GTS"),
        profile("assetto-ks-mazda-rx7-spirit-r", "Ks Mazda Rx7 Spirit R"),
        profile("assetto-ks-mazda-rx7-tuned", "Ks Mazda Rx7 Tuned"),
        profile("assetto-ks-mclaren-570s", "Ks Mclaren 570S"),
        profile("assetto-ks-mclaren-650-gt3", "Ks Mclaren 650 Gt3"),
        profile("assetto-ks-mclaren-p1", "Ks Mclaren P1"),
        profile("assetto-ks-mclaren-p1-gtr", "Ks Mclaren P1 Gtr"),
        profile("assetto-ks-mercedes-190-evo2", "Ks Mercedes 190 Evo2"),
        profile("assetto-ks-nissan-gtr-gt3", "Ks Nissan Gtr Gt3"),
        profile("assetto-ks-pagani-huayra-bc", "Ks Pagani Huayra Bc"),
        profile("assetto-ks-porsche-718-boxster-s", "Ks Porsche 718 Boxster S"),
        profile("assetto-ks-porsche-718-boxster-s-pdk", "Ks Porsche 718 Boxster S Pdk"),
        profile("assetto-ks-porsche-718-cayman-s", "Ks Porsche 718 Cayman S"),
        profile("assetto-ks-porsche-718-spyder-rs", "Ks Porsche 718 Spyder Rs"),
        profile("assetto-ks-porsche-911-gt3-cup-2017", "Ks Porsche 911 Gt3 Cup 2017"),
        profile("assetto-ks-porsche-911-gt3-r-2016", "Ks Porsche 911 Gt3 R 2016"),
        profile("assetto-ks-porsche-911-r", "Ks Porsche 911 R"),
        profile("assetto-ks-porsche-911-rsr-2017", "Ks Porsche 911 Rsr 2017"),
        profile("assetto-ks-porsche-918-spyder", "Ks Porsche 918 Spyder"),
        profile("assetto-ks-porsche-919-hybrid-2015", "Ks Porsche 919 Hybrid 2015"),
        profile("assetto-ks-porsche-919-hybrid-2016", "Ks Porsche 919 Hybrid 2016"),
        profile("assetto-ks-porsche-991-carrera-s", "Ks Porsche 991 Carrera S"),
        profile("assetto-ks-porsche-cayenne", "Ks Porsche Cayenne"),
        profile("assetto-ks-porsche-cayman-gt4-clubsport", "Ks Porsche Cayman Gt4 Clubsport"),
        profile("assetto-ks-porsche-cayman-gt4-std", "Ks Porsche Cayman Gt4 Std"),
        profile("assetto-ks-porsche-macan", "Ks Porsche Macan"),
        profile("assetto-ks-porsche-panamera", "Ks Porsche Panamera"),
        profile("assetto-ks-praga-r1", "Ks Praga R1"),
        profile("assetto-ks-ruf-rt12r-awd", "Ks Ruf Rt12R Awd"),
        profile("assetto-ks-toyota-gt86", "Ks Toyota Gt86"),
        profile("assetto-ks-toyota-supra-mkiv-drift", "Toyota Supra MKIV Drift"),
        profile("assetto-ks-toyota-supra-mkiv-tuned", "Ks Toyota Supra Mkiv Tuned"),
        profile("assetto-ks-toyota-ts040", "Ks Toyota Ts040"),
        profile("assetto-ktm-xbow-r", "Ktm Xbow R"),
        profile("assetto-lamborghini-aventador-sv", "Lamborghini Aventador SV"),
        profile("assetto-lamborghini-gallardo-sl", "Lamborghini Gallardo Superleggera"),
        profile("assetto-lamborghini-huracan-performante", "Lamborghini Huracán Performante"),
        profile("assetto-lamborghini-huracan-st", "Lamborghini Huracán ST"),
        profile("assetto-mclaren-mp412c", "Mclaren Mp412C"),
        profile("assetto-mclaren-mp412c-gt3", "Mclaren Mp412C Gt3"),
        profile("assetto-mercedes-amg-gt3", "Mercedes-AMG GT3"),
        profile("assetto-mercedes-sls", "Mercedes Sls"),
        profile("assetto-mercedes-sls-gt3", "Mercedes Sls Gt3"),
        profile("assetto-nissan-370z", "Nissan 370Z"),
        profile("assetto-nissan-gtr", "Nissan GT-R"),
        profile("assetto-nissan-skyline-r34", "Nissan Skyline GT-R R34"),
        profile("assetto-p4-5-2011", "P4 5 2011"),
        profile("assetto-pagani-huayra", "Pagani Huayra"),
        profile("assetto-pagani-zonda-r", "Pagani Zonda R"),
        profile("assetto-porsche-911-gt3-rs", "Porsche 911 GT3 RS"),
        profile("assetto-porsche-991-turbo-s", "Porsche 911 Turbo S (991)"),
        profile("assetto-tatuusfa1", "Tatuusfa1"),
        profile("assetto-toyota-supra-mkiv", "Toyota Supra Mk IV"),
        profile("modded-aston-martin-dbrs9-gt3", "Aston Martin DBS", moddedCarsPackId),
        profile("modded-audi-r8-lms-gt2", "Audi R8", moddedCarsPackId),
        profile("modded-audi-tt-cup-2015", "Audi TT", moddedCarsPackId),
        profile("modded-bmw-m8-gtlm", "BMW M8 Competition", moddedCarsPackId),
        profile("modded-bugatti-chiron-pur-sport", "Bugatti Chiron", moddedCarsPackId),
        profile("modded-cadillac-escalade-esv", "Cadillac Escalade", moddedCarsPackId),
        profile("modded-chevrolet-camaro-concept", "Chevrolet Camaro", moddedCarsPackId),
        profile("modded-chevrolet-corvette-c6-z06-stanced", "Chevrolet Corvete C6 ZO6", moddedCarsPackId),
        profile("modded-chevrolet-corvette-c7-stingray-hellspec", "Chevrolet Corvette Singray", moddedCarsPackId),
        profile("modded-ferrari-360-challenge-stradale", "Ferrari 360", moddedCarsPackId),
        profile("modded-ferrari-458-italia-gte-ferruccio", "Ferrari 458 Spider", moddedCarsPackId),
        profile("modded-ferrari-458-italia-tune", "Ferrari 458 Italia", moddedCarsPackId),
        profile("modded-ferrari-488-gte-evo-michelotto", "Ferrari 488 Pista", moddedCarsPackId),
        profile("modded-ferrari-f1-2000", "Ferrari F1 2000", moddedCarsPackId),
        profile("modded-ferrari-f430-gt2-2007", "Ferrari 430", moddedCarsPackId),
        profile("modded-ferrari-laferrari-trio", "Ferrari LaFerrari", moddedCarsPackId),
        profile("modded-ferrari-sf90-xx-stradale-2024", "Ferrari SF90 Stradale", moddedCarsPackId),
        profile("modded-lamborghini-aventador-sv", "Lamborghini Aventador SV", moddedCarsPackId),
        profile("modded-lamborghini-huracan-trofeo-evo2", "Lamborghini Huracan Trofeo EVO2 Hybrid", moddedCarsPackId),
        profile("modded-lexus-lfa", "Lexus LFA", moddedCarsPackId),
        profile("modded-lexus-lfa-concept-gt500", "Lexus LFA Concept GT500", moddedCarsPackId),
        profile("modded-lexus-lfa-no-hesi-spec", "Lexus LFA No Hesi Spec", moddedCarsPackId),
        profile("modded-lexus-lfa-nurburgring-edition", "Lexus LFA Nurburgring Edition", moddedCarsPackId),
        profile("modded-mercedes-amg-project-one-hypercar", "Mercedes-AMG Project One Hypercar", moddedCarsPackId),
        profile("modded-mercedes-benz-amg-gt3-evo-2020-sprint", "Mercedes-Benz AMG GT3 EVO 2020", moddedCarsPackId),
        profile("modded-mitsubishi-eclipse-gsx-r", "Mitsubishi Eclipse", moddedCarsPackId),
        profile("modded-mitsubishi-lancer-evolution-viii-gsr", "Mitsubishi Lance Evolution VII", moddedCarsPackId),
        profile("modded-nissan-350z", "Nissan 350z", moddedCarsPackId),
        profile("modded-nissan-370z-widebody", "Nissan 370Z Widebody", moddedCarsPackId),
        profile("modded-nissan-gt-r-nismo-godzilla", "Nissan GT-R NISMO Godzilla", moddedCarsPackId),
        profile("modded-porsche-911-992-turbo-s-pdk", "Porsche 911 Turbo S PDK", moddedCarsPackId),
        profile("modded-porsche-911-gt3-rs-hellspec", "Porsche 911 GT3 RS", moddedCarsPackId),
        profile("modded-porsche-911-turbo-s", "Porsche 911 Turbo S", moddedCarsPackId),
        profile("modded-porsche-carrera-gt-rs", "Porsche Carrera GT", moddedCarsPackId),
        profile("modded-toyota-supra-wangan", "Toyota Supra", moddedCarsPackId),
    )

    fun find(id: String?): FmodBankProfile = all.firstOrNull { it.id == id } ?: default

    fun adjacent(currentId: String, offset: Int): FmodBankProfile {
        val current = all.indexOfFirst { it.id == currentId }.coerceAtLeast(0)
        return all[(current + offset).mod(all.size)]
    }

    private fun profile(
        id: String,
        displayName: String,
        packGroup: String = originalCarsPackId,
    ): FmodBankProfile = FmodBankProfile(
        id = id,
        displayName = displayName,
        previewAssetName = "car_previews/$id.jpg",
        packGroup = packGroup,
    )
}
