package com.gabrielpc.enginesoundsimulator.audio

/**
 * Source-bank effect availability measured by the WAV pack exporter. A car is
 * only wired to a layer when its own FMOD event produced audible PCM; empty
 * entries are intentional rather than a generic sound fallback.
 */
internal enum class GenericCarEffect {
    TRANSMISSION,
    SHIFT_UP,
    SHIFT_DOWN,
    TURBO_LOOP,
    TURBO_DUMP,
    LIMITER,
    OVERRUN,
}

internal data class GenericCarEffectAvailability(
    val cabin: Set<GenericCarEffect>,
    val exterior: Set<GenericCarEffect>,
)

internal val genericCarEffectAvailability = mapOf(
    "alfa-romeo-4c" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "assetto-audi-r8-lms-2016" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "assetto-audi-r8-plus" to GenericCarEffectAvailability(setOf(GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "assetto-audi-tt-cup" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "assetto-bmw-m4" to GenericCarEffectAvailability(setOf(GenericCarEffect.OVERRUN), setOf(GenericCarEffect.OVERRUN)),
    "assetto-corvette-c7-stingray" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "assetto-ferrari-458-gt2" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "assetto-ferrari-458" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN)),
    "assetto-ferrari-488-gt3" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "assetto-ferrari-488-gtb" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "assetto-ferrari-fxx-k" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "assetto-ferrari-laferrari" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "assetto-lamborghini-aventador-sv" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "assetto-lamborghini-gallardo-sl" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "assetto-lamborghini-huracan-performante" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "assetto-lamborghini-huracan-st" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "assetto-mercedes-amg-gt3" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "assetto-nissan-370z" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "assetto-nissan-gtr" to GenericCarEffectAvailability(setOf(GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER), setOf(GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER)),
    "assetto-porsche-911-gt3-rs" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "assetto-porsche-991-turbo-s" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.OVERRUN)),
    "assetto-toyota-supra-mkiv" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "aston-martin-dbrs9-gt3" to GenericCarEffectAvailability(emptySet(), emptySet()),
    "audi-r8-lms-gt2" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "audi-tt-cup-2015" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "bmw-m8-gtlm" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER)),
    "bugatti-chiron-pur-sport" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER)),
    "cadillac-escalade-esv" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "chevrolet-camaro-concept" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "chevrolet-corvette-c6-z06-stanced" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN), emptySet()),
    "chevrolet-corvette-c7-stingray-hellspec" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN), emptySet()),
    "ferrari-360-challenge-stradale" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "ferrari-458-italia-gte-ferruccio" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "ferrari-458-italia-tune" to GenericCarEffectAvailability(emptySet(), emptySet()),
    "ferrari-488-gte-evo-michelotto" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "ferrari-f1-2000" to GenericCarEffectAvailability(emptySet(), emptySet()),
    "ferrari-f430-gt2-2007" to GenericCarEffectAvailability(setOf(GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "ferrari-laferrari-trio" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN)),
    "ferrari-sf90-xx-stradale-2024" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "lexus-lfa-no-hesi-spec" to GenericCarEffectAvailability(emptySet(), emptySet()),
    "lexus-lfa-nurburgring-edition" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "lexus-lfa" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "mercedes-amg-project-one-hypercar" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION), setOf(GenericCarEffect.TRANSMISSION)),
    "mercedes-benz-amg-gt3-evo-2020-sprint" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.OVERRUN)),
    "mitsubishi-eclipse-gsx-r" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.OVERRUN)),
    "mitsubishi-lancer-evolution-viii-gsr" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "nissan-350z" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "nissan-gt-r-nismo-godzilla" to GenericCarEffectAvailability(setOf(GenericCarEffect.LIMITER), setOf(GenericCarEffect.LIMITER)),
    "porsche-911-992-turbo-s-pdk" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP, GenericCarEffect.LIMITER, GenericCarEffect.OVERRUN)),
    "porsche-911-gt3-rs-hellspec" to GenericCarEffectAvailability(setOf(GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.SHIFT_DOWN, GenericCarEffect.OVERRUN)),
    "porsche-911-turbo-s" to GenericCarEffectAvailability(emptySet(), emptySet()),
    "porsche-carrera-gt-rs" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.OVERRUN), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.OVERRUN)),
    "toyota-supra-wangan" to GenericCarEffectAvailability(setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP), setOf(GenericCarEffect.TRANSMISSION, GenericCarEffect.SHIFT_UP, GenericCarEffect.SHIFT_DOWN, GenericCarEffect.TURBO_LOOP, GenericCarEffect.TURBO_DUMP)),
)
